### ISSUE TITLE
Fail to synchronize the hardware timestamp

### ISSUE THREAD

**Issue by skylighterQAQ** [MattsProjects/PylonSample_Stereo_Acquisition_PTP#1]
we have two cameras in different subnet, but we manage to synchronize them with computer by PTP. The offset between each camera and the host is less than 30 ticks. But the hardware time stamp difference between the two cameras is about 0.1s. 

Anyone got the same? Any advice?

Thanks.

**Comment by johnzjq** [comment]
@MattsProjects  Hi Mattew, we @skylighterQAQ  have tried the official code example of the synchronous free run (https://docs.baslerweb.com/synchronous-free-run). All the cameras are synchronized by ptp4l using the system as the master. By fetching the OffsetFromMaster value, we found multiple cameras seemed to be synchronized (the largest offset is -27 ticks). However, when we tried to retrieve the images using your code, the timestamps suggested there are about 0.1 seconds (1e8 ticks) difference between two images. Would you please provide some suggestions? Thanks!

**Comment by johnzjq** [comment]
It seems been sovled by restarting the computer...
